version: "3"
services:
    frontend:
        container_name: foodmate_client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: n9745734/foodmate_client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app/client
    backend:
        container_name: foodmate_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: n9745734/foodmate_server
        ports:
            - "8001:8001"
        volumes:
            - ./server:/usr/src/app/server
